name: social
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  animations: ^2.0.7
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.5.2
  cupertino_icons: ^1.0.2
  file_picker: ^5.2.7
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  firebase_messaging: ^14.6.2
  firebase_storage: ^11.1.1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_local_notifications: ^14.0.0+2
  flutter_svg: 2.0.5
  go_router: ^6.5.7
  hidable: ^1.0.3
  image_picker: ^0.8.7+4
  intl: ^0.18.1
  logger: ^1.3.0
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  shimmer: ^3.0.0
  story: ^1.0.0+1
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icons/
    - assets/images/
  uses-material-design: true
  fonts:
    - family: HKGrotesk
      fonts:
        - asset: assets/fonts/HKGrotesk-Black.otf
        - asset: assets/fonts/HKGrotesk-Bold.otf
        - asset: assets/fonts/HKGrotesk-Medium.otf
        - asset: assets/fonts/HKGrotesk-SemiBold.otf
